name: MediScribe CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run Build
      run: npm run build
      env:
        NEXT_TELEMETRY_DISABLED: 1
        NEXT_PUBLIC_FIREBASE_API_KEY: "AIzaSy_mock_api_key_for_build_only_123"
        NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: "mock.firebaseapp.com"
        NEXT_PUBLIC_FIREBASE_PROJECT_ID: "mock-project"
        NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: "mock-project.appspot.com"
        NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: "1234567890"
        NEXT_PUBLIC_FIREBASE_APP_ID: "1:1234567890:web:mockappid"
